# Generated by Django 5.2.14 on 2026-05-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeccionAprendida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('sector', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('desarrollo', 'Desarrollo Social')], max_length=20)),
                ('institucion', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('impacto_medido', models.CharField(blank=True, max_length=200)),
                ('anio', models.PositiveSmallIntegerField(default=2024)),
            ],
            options={
                'verbose_name': 'Lección aprendida',
                'verbose_name_plural': 'Lecciones aprendidas',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='edomex-diabetes', unique=True)),
                ('nombre', models.CharField(max_length=300)),
                ('objetivo', models.TextField()),
                ('enfoque', models.TextField()),
                ('analogia', models.JSONField(default=dict)),
                ('metas_globales', models.JSONField(default=dict)),
                ('indicadores', models.JSONField(default=dict)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Proyecto de referencia',
                'verbose_name_plural': 'Proyectos de referencia',
            },
        ),
        migrations.CreateModel(
            name='EjeAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=200)),
                ('acciones', models.JSONField(default=list)),
                ('meta', models.CharField(max_length=200)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejes_accion', to='proyectos.proyectoreferencia')),
            ],
            options={
                'verbose_name': 'Eje de acción',
                'verbose_name_plural': 'Ejes de acción',
                'ordering': ['numero'],
                'unique_together': {('proyecto', 'numero')},
            },
        ),
    ]
