# Generated by Django 5.2.14 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('grupo', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('aportacion', models.TextField()),
                ('dato_clave', models.TextField()),
                ('fuente', models.CharField(max_length=200)),
                ('nivel_confiabilidad', models.PositiveSmallIntegerField(default=85)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FuenteInformacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('gubernamental', 'Gubernamental'), ('academica', 'Académica'), ('internacional', 'Internacional'), ('tradicional', 'Saberes tradicionales')], max_length=20)),
                ('url_api', models.URLField(blank=True)),
                ('nivel_confiabilidad', models.PositiveSmallIntegerField(default=80)),
                ('activa', models.BooleanField(default=True)),
                ('ultima_sincronizacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fuente de información',
                'verbose_name_plural': 'Fuentes de información',
            },
        ),
    ]
