# Generated by Django 5.2.14 on 2026-05-27 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista MITA'), ('investigador', 'Investigador SNI'), ('dependencia', 'Dependencia Gubernamental'), ('auditor', 'Auditor'), ('publico', 'Público General')], default='analista', max_length=20),
        ),
        migrations.CreateModel(
            name='ReporteCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_control', models.CharField(db_index=True, max_length=30, unique=True)),
                ('eje', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('corrupcion', 'Corrupción'), ('economia', 'Economía'), ('empleo', 'Empleo'), ('seguridad', 'Seguridad')], max_length=20)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('datos_captura', models.JSONField(blank=True, default=dict)),
                ('municipio', models.CharField(blank=True, max_length=120)),
                ('dependencia_principal', models.CharField(max_length=200)),
                ('dependencias_involucradas', models.JSONField(blank=True, default=list)),
                ('ruta_tramite', models.JSONField(blank=True, default=list)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('turnado', 'Turnado a dependencia'), ('en_atencion', 'En atención'), ('resuelto', 'Resuelto'), ('no_procede', 'No procede')], default='recibido', max_length=20)),
                ('respuesta_dependencia', models.TextField(blank=True)),
                ('fecha_estimada_atencion', models.DateField(blank=True, null=True)),
                ('motivo_no_procede', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ciudadanos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reporte ciudadano',
                'verbose_name_plural': 'Reportes ciudadanos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MensajeReporteCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sesion_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tipo_autor', models.CharField(choices=[('ciudadano', 'Ciudadano'), ('ia', 'Asistente IA MITA'), ('dependencia', 'Dependencia'), ('sistema', 'Sistema')], max_length=20)),
                ('autor_nombre', models.CharField(max_length=120)),
                ('contenido', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.reporteciudadano')),
            ],
            options={
                'verbose_name': 'Mensaje de reporte',
                'verbose_name_plural': 'Mensajes de reportes',
                'ordering': ['creado_en'],
            },
        ),
    ]
