# Generated by Django 5.1.5 on 2026-05-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_perfilusuario_rol_reporteciudadano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteciudadano',
            name='responsable_atencion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='mensajereporteciudadano',
            name='tipo_autor',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('ia', 'Asistente IA MITA'), ('dependencia', 'Dependencia'), ('responsable', 'Responsable de atención'), ('sistema', 'Sistema')], max_length=20),
        ),
    ]
