# Generated by Django 5.2.14 on 2026-05-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilSNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('area', models.CharField(max_length=150)),
                ('nivel', models.CharField(max_length=50)),
                ('funcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Perfil SNI',
                'verbose_name_plural': 'Perfiles SNI',
            },
        ),
        migrations.CreateModel(
            name='InvestigadorSNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('area_especialidad', models.CharField(max_length=200)),
                ('nivel_snii', models.CharField(max_length=20)),
                ('institucion', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponible', models.BooleanField(default=True)),
                ('perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigadores', to='sni.perfilsni')),
            ],
            options={
                'verbose_name': 'Investigador SNI',
                'verbose_name_plural': 'Investigadores SNI',
            },
        ),
    ]
