"""Catálogo de centros de salud, hospitales y UMF en el Estado de México (SEDESA / ISSEM / IMSS-Bienestar)."""

CENTROS_SALUD_EDOMEX = [
    # Ecatepec
    {"slug": "hg-ecatepec-americas", "nombre": "Hospital General Ecatepec Las Américas", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Ecatepec", "lat": 19.6018, "lng": -99.0502, "direccion": "Av. Las Américas s/n, San Cristóbal Centro, Ecatepec",
     "telefono": "55-5777-7000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM — Corredor Oriente."},
    {"slug": "cs-ecatepec-jardines-morelos", "nombre": "Centro de Salud Jardines de Morelos", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Ecatepec", "lat": 19.6085, "lng": -99.0420, "direccion": "Calle Jardines de Morelos, Ecatepec",
     "telefono": "55-5777-1201", "horario": "L–V 8:00–16:00", "descripcion": "Unidad de atención primaria ISSEM."},
    {"slug": "cs-ecatepec-ciudad-azteca", "nombre": "Centro de Salud Ciudad Azteca", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Ecatepec", "lat": 19.6130, "lng": -99.0350, "direccion": "Av. Central Ciudad Azteca, Ecatepec",
     "telefono": "55-5777-1202", "horario": "L–V 8:00–16:00", "descripcion": "Consulta general y medicamentos básicos."},
    {"slug": "cs-ecatepec-san-cristobal", "nombre": "Centro de Salud San Cristóbal Centro", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Ecatepec", "lat": 19.5980, "lng": -99.0580, "direccion": "Av. Central San Cristóbal, Ecatepec",
     "telefono": "55-5777-1203", "horario": "L–V 8:00–15:00", "descripcion": "Atención primaria SEDESA."},
    {"slug": "umf-83-ecatepec", "nombre": "UMF No. 83 Ecatepec (IMSS-Bienestar)", "eje": "salud", "tipo": "Unidad de medicina familiar",
     "municipio": "Ecatepec", "lat": 19.5950, "lng": -99.0450, "direccion": "Av. Central s/n, Ecatepec",
     "telefono": "55-5777-4500", "horario": "L–V 8:00–20:00", "descripcion": "IMSS-Bienestar — crónicos-degenerativos."},
    # Nezahualcóyotl
    {"slug": "hg-nezahualcoyotl", "nombre": "Hospital General Nezahualcóyotl", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Nezahualcóyotl", "lat": 19.4006, "lng": -99.0148, "direccion": "Av. Chimalhuacán s/n, Nezahualcóyotl",
     "telefono": "55-5793-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Nezahualcóyotl."},
    {"slug": "cs-neza-sector-popular", "nombre": "Centro de Salud Sector Popular", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Nezahualcóyotl", "lat": 19.4050, "lng": -99.0180, "direccion": "Sector Popular, Nezahualcóyotl",
     "telefono": "55-5793-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    {"slug": "cs-neza-valle-aragon", "nombre": "Centro de Salud Valle de Aragón", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Nezahualcóyotl", "lat": 19.4880, "lng": -99.0100, "direccion": "Valle de Aragón, Nezahualcóyotl",
     "telefono": "55-5793-1202", "horario": "L–V 8:00–16:00", "descripcion": "Consulta y vacunación."},
    {"slug": "umf-67-neza", "nombre": "UMF No. 67 Nezahualcóyotl (IMSS-Bienestar)", "eje": "salud", "tipo": "Unidad de medicina familiar",
     "municipio": "Nezahualcóyotl", "lat": 19.3920, "lng": -99.0220, "direccion": "Av. Pantitlán, Nezahualcóyotl",
     "telefono": "55-5793-4500", "horario": "L–V 8:00–20:00", "descripcion": "IMSS-Bienestar — medicamentos crónicos."},
    # Toluca
    {"slug": "hg-toluca", "nombre": "Hospital General Toluca", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Toluca", "lat": 19.2826, "lng": -99.6557, "direccion": "Av. Instituto Literario 100, Col. Universitario, Toluca",
     "telefono": "722-215-0500", "horario": "24 h urgencias", "descripcion": "Hospital estatal de referencia."},
    {"slug": "hmp-monica-pretelini", "nombre": "Hospital Materno Perinatal Mónica Pretelini", "eje": "salud", "tipo": "Hospital materno-perinatal",
     "municipio": "Toluca", "lat": 19.2780, "lng": -99.6520, "direccion": "Paseo Tollocan s/n, Toluca",
     "telefono": "722-215-0600", "horario": "24 h", "descripcion": "Atención materno-infantil ISSEM."},
    {"slug": "hese-edomex", "nombre": "Hospital de Especialidades del Estado de México", "eje": "salud", "tipo": "Hospital de especialidades",
     "municipio": "Toluca", "lat": 19.2850, "lng": -99.6580, "direccion": "Av. Guerrero 200, Toluca",
     "telefono": "722-215-0700", "horario": "L–V 7:00–19:00", "descripcion": "Cardiología, nefrología, endocrinología."},
    {"slug": "cs-toluca-centro", "nombre": "Centro de Salud Toluca Centro", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Toluca", "lat": 19.2920, "lng": -99.6540, "direccion": "Av. Independencia 200, Toluca",
     "telefono": "722-215-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    {"slug": "hospital-issemym-toluca", "nombre": "Hospital ISSEMYM Toluca", "eje": "salud", "tipo": "Hospital ISSEMYM",
     "municipio": "Toluca", "lat": 19.2760, "lng": -99.6610, "direccion": "Av. Issemym s/n, Toluca",
     "telefono": "722-215-8000", "horario": "L–V 8:00–18:00", "descripcion": "Derechohabientes ISSEMYM."},
    {"slug": "farmacia-estatal-toluca", "nombre": "Farmacia Estatal Toluca (SEDESA)", "eje": "salud", "tipo": "Farmacia estatal",
     "municipio": "Toluca", "lat": 19.2910, "lng": -99.6560, "direccion": "Paseo Tollocan 400, Toluca",
     "telefono": "722-215-1200", "horario": "L–S 9:00–18:00", "descripcion": "Medicamentos gratuitos con receta."},
    # Chalco
    {"slug": "hg-chalco", "nombre": "Hospital General Chalco", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Chalco", "lat": 19.2617, "lng": -98.8975, "direccion": "Av. Solidaridad 200, Chalco",
     "telefono": "55-5971-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Chalco."},
    {"slug": "cs-chalco-solidaridad", "nombre": "Centro de Salud Chalco Solidaridad", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Chalco", "lat": 19.2580, "lng": -98.8920, "direccion": "Col. Solidaridad, Chalco",
     "telefono": "55-5971-1201", "horario": "L–V 8:00–15:00", "descripcion": "Atención primaria Corredor Oriente."},
    # Valle de Chalco
    {"slug": "hg-valle-chalco", "nombre": "Hospital General Valle de Chalco Solidaridad", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Valle de Chalco", "lat": 19.2892, "lng": -98.9528, "direccion": "Av. Zaragoza s/n, Valle de Chalco",
     "telefono": "55-5864-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM."},
    {"slug": "cs-valle-chalco", "nombre": "Centro de Salud Valle de Chalco", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Valle de Chalco", "lat": 19.2850, "lng": -98.9480, "direccion": "Av. Guadalupana, Valle de Chalco",
     "telefono": "55-5864-1201", "horario": "L–V 8:00–16:00", "descripcion": "Consulta general ISSEM."},
    # Ixtapaluca
    {"slug": "hg-ixtapaluca", "nombre": "Hospital General Ixtapaluca", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Ixtapaluca", "lat": 19.3167, "lng": -98.8833, "direccion": "Av. Cuauhtémoc s/n, Ixtapaluca",
     "telefono": "55-5972-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Ixtapaluca."},
    {"slug": "cs-ixtapaluca", "nombre": "Centro de Salud Ixtapaluca", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Ixtapaluca", "lat": 19.3120, "lng": -98.8880, "direccion": "Centro, Ixtapaluca",
     "telefono": "55-5972-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria."},
    # Naucalpan
    {"slug": "hg-naucalpan", "nombre": "Hospital General Naucalpan", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Naucalpan", "lat": 19.4785, "lng": -99.2396, "direccion": "Av. Gustavo Baz 312, Naucalpan",
     "telefono": "55-5393-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Naucalpan."},
    {"slug": "cs-naucalpan-satellite", "nombre": "Centro de Salud Satélite", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Naucalpan", "lat": 19.5020, "lng": -99.2380, "direccion": "Ciudad Satélite, Naucalpan",
     "telefono": "55-5393-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    # Tlalnepantla
    {"slug": "hg-tlalnepantla", "nombre": "Hospital General Tlalnepantla", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Tlalnepantla", "lat": 19.5400, "lng": -99.1950, "direccion": "Av. Hidalgo s/n, Tlalnepantla",
     "telefono": "55-5366-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM."},
    {"slug": "cs-tlalnepantla-madero", "nombre": "Centro de Salud Tenayuca", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Tlalnepantla", "lat": 19.5280, "lng": -99.1880, "direccion": "Tenayuca, Tlalnepantla",
     "telefono": "55-5366-1201", "horario": "L–V 8:00–16:00", "descripcion": "Consulta y medicamentos."},
    # Cuautitlán Izcalli
    {"slug": "hg-cuautitlan-izcalli", "nombre": "Hospital General Cuautitlán Izcalli", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Cuautitlán Izcalli", "lat": 19.6469, "lng": -99.2464, "direccion": "Av. Primero de Mayo s/n, Cuautitlán Izcalli",
     "telefono": "55-5873-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM."},
    {"slug": "cs-cuautitlan-izcalli", "nombre": "Centro de Salud Cuautitlán Izcalli", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Cuautitlán Izcalli", "lat": 19.6420, "lng": -99.2420, "direccion": "Centro Urbano, Cuautitlán Izcalli",
     "telefono": "55-5873-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria."},
    # Chimalhuacán
    {"slug": "cs-chimalhuacan", "nombre": "Centro de Salud Chimalhuacán", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Chimalhuacán", "lat": 19.4215, "lng": -98.9500, "direccion": "Av. Nezahualcóyotl s/n, Chimalhuacán",
     "telefono": "55-5892-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    {"slug": "hg-chimalhuacan", "nombre": "Hospital General Chimalhuacán", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Chimalhuacán", "lat": 19.4180, "lng": -98.9550, "direccion": "Av. Bordo de Xochiaca, Chimalhuacán",
     "telefono": "55-5892-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM."},
    # Texcoco
    {"slug": "hg-texcoco", "nombre": "Hospital General Texcoco", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Texcoco", "lat": 19.5130, "lng": -98.8820, "direccion": "Av. Juárez s/n, Texcoco",
     "telefono": "595-954-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Texcoco."},
    {"slug": "cs-texcoco", "nombre": "Centro de Salud Texcoco Centro", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Texcoco", "lat": 19.5100, "lng": -98.8780, "direccion": "Centro, Texcoco",
     "telefono": "595-954-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria."},
    # Metepec
    {"slug": "cs-metepec", "nombre": "Centro de Salud Metepec", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Metepec", "lat": 19.2517, "lng": -99.6044, "direccion": "Av. Estado de México 50, Metepec",
     "telefono": "722-271-1201", "horario": "L–V 8:00–16:00", "descripcion": "Consulta general ISSEM."},
    {"slug": "hg-metepec", "nombre": "Hospital General Metepec", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Metepec", "lat": 19.2480, "lng": -99.6080, "direccion": "Av. Tecnológico s/n, Metepec",
     "telefono": "722-271-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Metepec."},
    # Zumpango
    {"slug": "hg-zumpango", "nombre": "Hospital General Zumpango", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Zumpango", "lat": 19.7965, "lng": -99.1010, "direccion": "Av. Insurgentes s/n, Zumpango",
     "telefono": "591-918-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM Zumpango."},
    {"slug": "cs-zumpango", "nombre": "Centro de Salud Zumpango", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Zumpango", "lat": 19.7920, "lng": -99.0980, "direccion": "Centro, Zumpango",
     "telefono": "591-918-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria."},
    # Atizapán de Zaragoza
    {"slug": "hg-atizapan", "nombre": "Hospital General Atizapán de Zaragoza", "eje": "salud", "tipo": "Hospital general",
     "municipio": "Atizapán de Zaragoza", "lat": 19.5640, "lng": -99.2600, "direccion": "Av. Adolfo López Mateos s/n, Atizapán",
     "telefono": "55-5829-5000", "horario": "24 h urgencias", "descripcion": "Hospital General ISSEM."},
    {"slug": "cs-atizapan", "nombre": "Centro de Salud Atizapán Centro", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Atizapán de Zaragoza", "lat": 19.5600, "lng": -99.2550, "direccion": "Centro, Atizapán de Zaragoza",
     "telefono": "55-5829-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    # Tultitlán
    {"slug": "cs-tultitlan", "nombre": "Centro de Salud Tultitlán", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Tultitlán", "lat": 19.6450, "lng": -99.1680, "direccion": "Av. Hidalgo s/n, Tultitlán",
     "telefono": "55-5899-1201", "horario": "L–V 8:00–16:00", "descripcion": "Consulta y vacunación."},
    # Coacalco
    {"slug": "cs-coacalco", "nombre": "Centro de Salud Coacalco", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Coacalco", "lat": 19.6290, "lng": -99.1010, "direccion": "Av. Zaragoza s/n, Coacalco",
     "telefono": "55-5889-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria ISSEM."},
    # Tecámac
    {"slug": "cs-tecamac", "nombre": "Centro de Salud Tecámac", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Tecámac", "lat": 19.7130, "lng": -98.9680, "direccion": "Av. Central s/n, Tecámac",
     "telefono": "55-5959-1201", "horario": "L–V 8:00–16:00", "descripcion": "Atención primaria."},
    # Lerma
    {"slug": "cs-lerma", "nombre": "Centro de Salud Lerma", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Lerma", "lat": 19.2869, "lng": -99.5097, "direccion": "Centro, Lerma de Villada",
     "telefono": "728-281-1201", "horario": "L–V 8:00–16:00", "descripcion": "Consulta general ISSEM."},
    # Atlacomulco
    {"slug": "hr-atlacomulco", "nombre": "Hospital Regional Atlacomulco", "eje": "salud", "tipo": "Hospital regional",
     "municipio": "Atlacomulco", "lat": 19.7997, "lng": -99.8736, "direccion": "Av. Revolución s/n, Atlacomulco",
     "telefono": "712-690-5000", "horario": "24 h urgencias", "descripcion": "Hospital Regional ISSEM — zona norte."},
    {"slug": "cs-atlacomulco", "nombre": "Centro de Salud Atlacomulco", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "Atlacomulco", "lat": 19.7950, "lng": -99.8700, "direccion": "Centro, Atlacomulco",
     "telefono": "712-690-1201", "horario": "L–V 8:00–15:00", "descripcion": "Atención primaria región indígena."},
    # El Oro
    {"slug": "cs-el-oro", "nombre": "Centro de Salud El Oro", "eje": "salud", "tipo": "Centro de salud",
     "municipio": "El Oro", "lat": 19.8031, "lng": -100.1314, "direccion": "Centro, El Oro",
     "telefono": "711-103-1201", "horario": "L–V 8:00–15:00", "descripcion": "Atención primaria zona mazahua-otomí."},
]

MUNICIPIOS_CON_CENTROS_SALUD = sorted({c['municipio'] for c in CENTROS_SALUD_EDOMEX})
