"""Datos semilla para la Plataforma MITA."""

DISCIPLINAS = [
    {"slug": "antropologia", "nombre": "Antropología", "grupo": "cecyctem", "area": "Ciencias Sociales",
     "aportacion": "Significados culturales, medicina tradicional, comunidades mazahua-otomí",
     "dato_clave": "Sin adaptación cultural, programas fallan 60%", "fuente": "CECyTEM / Revistas indexadas", "nivel_confiabilidad": 90},
    {"slug": "sociologia", "nombre": "Sociología", "grupo": "cecyctem", "area": "Ciencias Sociales",
     "aportacion": "Desigualdad, pobreza, hacinamiento",
     "dato_clave": "Riesgo +35% en oriente; estigma y ocultamiento → bajo apego", "fuente": "CECyTEM / Revistas indexadas", "nivel_confiabilidad": 88},
    {"slug": "pedagogia", "nombre": "Pedagogía", "grupo": "cecyctem", "area": "Educación",
     "aportacion": "Educación intercultural, materiales en lenguas originarias",
     "dato_clave": "Reduce complicaciones 40%", "fuente": "CECyTEM", "nivel_confiabilidad": 92},
    {"slug": "cecyctem", "nombre": "CECyTEM", "grupo": "cecyctem", "area": "Educación",
     "aportacion": "Formación técnica como multiplicador",
     "dato_clave": "78% mejora de conocimientos; impacto estudiante → familia → comunidad", "fuente": "CECyTEM", "nivel_confiabilidad": 95},
    {"slug": "economia_salud", "nombre": "Economía de la Salud", "grupo": "cecyctem", "area": "Administración y Economía",
     "aportacion": "Costo anual, gasto familiar, viabilidad financiera",
     "dato_clave": "Costo anual 9,200 mdp; gasto familiar 18–25 mil pesos/año (42% ingreso); prevenir = 5x más barato",
     "fuente": "Revistas indexadas", "nivel_confiabilidad": 90},
    {"slug": "gestion_publica", "nombre": "Gestión Pública", "grupo": "cecyctem", "area": "Administración y Economía",
     "aportacion": "Atención por barrio, horarios extendidos, coordinación institucional",
     "dato_clave": "Reducen abandono 25%; falta coordinación institucional", "fuente": "Revistas indexadas", "nivel_confiabilidad": 85},
    {"slug": "tecnologia_alimentaria", "nombre": "Tecnología Alimentaria", "grupo": "cecyctem", "area": "Alimentos y Biotecnología",
     "aportacion": "Productos tradicionales modificados, etiquetado",
     "dato_clave": "60% menos azúcar, misma aceptación (89%); enseñanza lectura → -35% consumo bebidas azucaradas",
     "fuente": "CECyTEM / Revistas indexadas", "nivel_confiabilidad": 91},
    {"slug": "informatica", "nombre": "Informática", "grupo": "cecyctem", "area": "Ingeniería y Tecnología",
     "aportacion": "Sistemas SMS/app ligera, interoperabilidad",
     "dato_clave": "+32% control glucémico; falta sistema único de datos entre instituciones", "fuente": "CECyTEM", "nivel_confiabilidad": 88},
    {"slug": "ingenieria_urbana", "nombre": "Ingeniería Urbana", "grupo": "cecyctem", "area": "Ingeniería y Tecnología",
     "aportacion": "Parques, banquetas, seguridad, diseño urbano",
     "dato_clave": "-18% prevalencia donde hay infraestructura adecuada", "fuente": "Revistas indexadas", "nivel_confiabilidad": 87},
    {"slug": "oms_ops", "nombre": "OMS/OPS", "grupo": "cecyctem", "area": "Internacional",
     "aportacion": "Referencias internacionales, modelos Brasil/Chile",
     "dato_clave": "Edomex = corredor de mayor riesgo en América Latina", "fuente": "OMS/OPS", "nivel_confiabilidad": 95},
    {"slug": "idf", "nombre": "IDF", "grupo": "cecyctem", "area": "Internacional",
     "aportacion": "Proyecciones epidemiológicas globales",
     "dato_clave": "Proyección 2.3 millones 2030 sin acción", "fuente": "International Diabetes Federation", "nivel_confiabilidad": 94},
    {"slug": "sedesa", "nombre": "SEDESA", "grupo": "gobierno", "area": "Salud Estatal",
     "aportacion": "Prevalencia, mortalidad, programas de detección y atención integrada",
     "dato_clave": "15.6% adultos = 1.9 millones; 8.2% sin diagnosticar; mortalidad 104/100 mil; control adecuado solo 31%",
     "fuente": "Gobierno del Estado de México", "nivel_confiabilidad": 98},
    {"slug": "issemym", "nombre": "ISSEMYM", "grupo": "gobierno", "area": "Salud Estatal",
     "aportacion": "Atención a derechohabientes, modelo por etapas",
     "dato_clave": "72,000 pacientes; 22% abandono; modelo etapas → -28% hospitalizaciones",
     "fuente": "Gobierno del Estado de México", "nivel_confiabilidad": 97},
    {"slug": "sedessem_dif", "nombre": "SEDESSEM / DIF", "grupo": "gobierno", "area": "Desarrollo Social",
     "aportacion": "Apoyos alimentarios, transferencias económicas",
     "dato_clave": "Transferencias $2,500 bimestrales; diabetes = grupo prioritario",
     "fuente": "Gobierno del Estado de México", "nivel_confiabilidad": 96},
    {"slug": "seem_cecyctem", "nombre": "SEEM + CECyTEM", "grupo": "gobierno", "area": "Educación",
     "aportacion": "Escuelas saludables, currículo con prevención",
     "dato_clave": "40% estudiantes con sobrepeso/obesidad", "fuente": "Gobierno del Estado de México", "nivel_confiabilidad": 95},
    {"slug": "finanzas", "nombre": "Finanzas", "grupo": "gobierno", "area": "Presupuesto",
     "aportacion": "Presupuesto etiquetado, inversión/ahorro",
     "dato_clave": "Presupuesto etiquetado insuficiente; falta visión de inversión/ahorro",
     "fuente": "Gobierno del Estado de México", "nivel_confiabilidad": 94},
]

ZONAS_GEO = [
    {"slug": "ecatepec", "nombre": "Ecatepec", "tipo": "hotspot", "corredor": "oriente", "lat": 19.6018, "lng": -99.0502,
     "prevalencia": 22.5, "mortalidad": 115, "pobreza": "alta", "descripcion": "Corredor Oriente — alta carga, hacinamiento, menor acceso"},
    {"slug": "nezahualcoyotl", "nombre": "Nezahualcóyotl", "tipo": "hotspot", "corredor": "oriente", "lat": 19.4006, "lng": -99.0148,
     "prevalencia": 23.0, "mortalidad": 112, "pobreza": "alta", "descripcion": "Corredor Oriente — 21–23% prevalencia, mortalidad >110/100 mil"},
    {"slug": "chalco", "nombre": "Chalco", "tipo": "hotspot", "corredor": "oriente", "lat": 19.2617, "lng": -98.8975,
     "prevalencia": 21.5, "mortalidad": 110, "pobreza": "alta", "descripcion": "Corredor Oriente — zona periférica con desiertos de atención"},
    {"slug": "ixtapaluca", "nombre": "Ixtapaluca", "tipo": "hotspot", "corredor": "oriente", "lat": 19.3167, "lng": -98.8833,
     "prevalencia": 21.0, "mortalidad": 108, "pobreza": "alta", "descripcion": "Corredor Oriente — alta densidad de refresquerías"},
    {"slug": "valle_chalco", "nombre": "Valle de Chalco", "tipo": "hotspot", "corredor": "oriente", "lat": 19.2892, "lng": -98.9528,
     "prevalencia": 22.0, "mortalidad": 111, "pobreza": "alta", "descripcion": "Corredor Oriente — marginación y falta de infraestructura"},
    {"slug": "toluca", "nombre": "Toluca", "tipo": "hotspot", "corredor": "conurbada", "lat": 19.2826, "lng": -99.6557,
     "prevalencia": 18.5, "mortalidad": 95, "pobreza": "media", "descripcion": "Zona Conurbada — alta densidad, obesidad, alimentación urbana"},
    {"slug": "lerma", "nombre": "Lerma", "tipo": "hotspot", "corredor": "conurbada", "lat": 19.2869, "lng": -99.5097,
     "prevalencia": 17.0, "mortalidad": 90, "pobreza": "media", "descripcion": "Zona Conurbada — transición urbano-rural"},
    {"slug": "metepec", "nombre": "Metepec", "tipo": "hotspot", "corredor": "conurbada", "lat": 19.2517, "lng": -99.6044,
     "prevalencia": 16.5, "mortalidad": 88, "pobreza": "media-baja", "descripcion": "Zona Conurbada — sedentarismo urbano"},
    {"slug": "atlacomulco", "nombre": "Atlacomulco", "tipo": "hotspot", "corredor": "indigena", "lat": 19.7997, "lng": -99.8736,
     "prevalencia": 19.0, "mortalidad": 100, "pobreza": "alta", "descripcion": "Región Indígena — barreras culturales, consumo alto azúcar/refrescos"},
    {"slug": "el_oro", "nombre": "El Oro", "tipo": "hotspot", "corredor": "indigena", "lat": 19.8031, "lng": -100.1314,
     "prevalencia": 18.5, "mortalidad": 98, "pobreza": "alta", "descripcion": "Región Indígena — 18–20% prevalencia"},
    {"slug": "san_felipe", "nombre": "San Felipe del Progreso", "tipo": "hotspot", "corredor": "indigena", "lat": 19.7117, "lng": -99.9514,
     "prevalencia": 20.0, "mortalidad": 102, "pobreza": "alta", "descripcion": "Región Indígena — comunidades mazahua-otomí"},
    {"slug": "naucalpan", "nombre": "Naucalpan", "tipo": "media", "corredor": "poniente", "lat": 19.4785, "lng": -99.2396,
     "prevalencia": 12.0, "mortalidad": 75, "pobreza": "baja", "descripcion": "Norte y poniente — mejores ingresos, 10–13%"},
    {"slug": "atizapan", "nombre": "Atizapán", "tipo": "baja", "corredor": "poniente", "lat": 19.5686, "lng": -99.2453,
     "prevalencia": 11.0, "mortalidad": 70, "pobreza": "baja", "descripcion": "Norte y poniente — menor densidad, mejores ingresos"},
]

CAPAS_GEO = [
    {"slug": "salud", "nombre": "Salud", "descripcion": "Distancia a clínicas, disponibilidad de medicamentos — desiertos de atención en colonias periféricas"},
    {"slug": "social", "nombre": "Social", "descripcion": "Marginación, educación, ingreso — correlación directa: más pobreza = más diabetes"},
    {"slug": "ambiental", "nombre": "Ambiental", "descripcion": "Parques, seguridad, banquetas — donde hay infraestructura, -18% riesgo"},
    {"slug": "alimentaria", "nombre": "Alimentaria", "descripcion": "Tiendas de conveniencia vs mercados — alta densidad de refresquerías = +25% riesgo"},
]

CRUCES_INTER = [
    {"disciplinas_texto": ["Antropología", "Salud"], "concepto": "Apego cultural vs apego terapéutico",
     "resultado": "Sin adaptar tratamientos a creencias, medicinas no funcionan. +60% abandono en zonas indígenas."},
    {"disciplinas_texto": ["Sociología", "Economía"], "concepto": "Ingreso → Alimentación → Riesgo → Costo",
     "resultado": "Hogares pobres gastan 42% ingreso en salud; prevenir ahorra 5x. La enfermedad es causa y consecuencia de pobreza."},
    {"disciplinas_texto": ["Educación", "Alimentos"], "concepto": "Formación técnica + Desarrollo de productos",
     "resultado": "Estudiantes CECyTEM crean alimentos saludables tradicionales → cambio de hábitos en familias."},
    {"disciplinas_texto": ["Ingeniería", "Geografía"], "concepto": "Infraestructura urbana → Actividad física → Prevalencia",
     "resultado": "Diseño de ciudad determina salud. Parques seguros = -18% diabetes."},
    {"disciplinas_texto": ["Administración", "Tecnología"], "concepto": "Gestión pública + Sistemas de información",
     "resultado": "Coordinación única → eliminar duplicidad, seguimiento real, reducir gasto."},
]

EJES_MITA = [
    {"slug": "multiinterdisciplina", "nombre": "Multiinterdisciplina", "sigla": "M",
     "descripcion": "Reúne y clasifica todo el conocimiento existente, sin excluir ninguna área del saber humano.",
     "proposito": "Contar con todos los métodos, variables, conceptos y procedimientos para analizar cualquier situación desde todos los ángulos.",
     "fuentes": ["Secretaría de Ciencias, Humanidades, Tecnología e Innovación", "Gobierno de México", "Revistas indexadas"]},
    {"slug": "interdisciplina", "nombre": "Interdisciplina", "sigla": "I",
     "descripcion": "Proceso mediante el cual se relacionan, conectan y hacen dialogar los diferentes saberes entre sí.",
     "proposito": "Generar una visión completa donde el conocimiento de una disciplina complementa y enriquece al de otra.",
     "fuentes": ["Algoritmos propios MITA", "Reglas de cruce exclusivas"]},
    {"slug": "interculturalidad", "nombre": "Interculturalidad", "sigla": "I",
     "descripcion": "Reconoce e integra en igualdad de valor el conocimiento científico-técnico y los saberes tradicionales.",
     "proposito": "Diseñar soluciones adecuadas, aceptadas y sostenibles que respeten identidad y cultura.",
     "fuentes": ["Trabajo de campo validado", "Comunidades originarias"]},
    {"slug": "transdisciplina", "nombre": "Transdisciplina", "sigla": "T",
     "descripcion": "Integración de los ejes anteriores para ver la realidad como un todo indivisible.",
     "proposito": "Generar soluciones completas que atienden todos los aspectos de un problema.",
     "fuentes": ["Síntesis integrada MITA"]},
    {"slug": "analogia", "nombre": "Analogía", "sigla": "A",
     "descripcion": "Comparar, medir, cotejar y ajustar cada dato, propuesta o solución contra parámetros válidos.",
     "proposito": "Garantizar que toda solución sea correcta, segura, eficaz y ajustada a la realidad y la ley.",
     "fuentes": ["Algoritmos analógicos exclusivos MITA"]},
]

PROCESO_OPERATIVO = [
    {"paso": 1, "nombre": "Definición del asunto", "descripcion": "Se identifica claramente qué problema, necesidad o proyecto se va a analizar."},
    {"paso": 2, "nombre": "Recopilación de conocimiento", "descripcion": "El sistema accede a toda la información válida relacionada con el tema."},
    {"paso": 3, "nombre": "Organización y relación", "descripcion": "Se ordenan los datos y se establecen conexiones entre áreas del saber."},
    {"paso": 4, "nombre": "Análisis y Analogía", "descripcion": "Se aplican algoritmos para medir, comparar y evaluar contra parámetros de calidad, ley y realidad."},
    {"paso": 5, "nombre": "Generación de opciones", "descripcion": "El sistema presenta alternativas de solución fundamentadas y viables."},
    {"paso": 6, "nombre": "Evaluación y selección", "descripcion": "Se analizan las opciones y se determina la más adecuada con respaldo técnico y legal."},
    {"paso": 7, "nombre": "Dictamen de Validación", "descripcion": "Se emite el documento oficial que certifica que la acción es correcta, válida y segura."},
]

EJES_ACCION = [
    {"numero": 1, "nombre": "Eje Territorial y Cultural", "origen": "Antropología + Geografía + Salud",
     "acciones": ["Mapa de atención: intervención diferenciada por zona", "Modelo intercultural: personal bilingüe, medicina tradicional + alópata", "Materiales adaptados culturalmente"],
     "meta": "Reducir abandono en zonas indígenas 35%"},
    {"numero": 2, "nombre": "Eje Educativo – CECyTEM como Motor", "origen": "Educación + Alimentos + Tecnología",
     "acciones": ["Currículo transversal con módulo certificado Salud y Comunidad", "Proyecto comunitario obligatorio — 120,000 agentes multiplicadores", "Laboratorios de alimentos: versiones saludables de comida mexiquense"],
     "meta": "70% de familias con cambios de hábitos"},
    {"numero": 3, "nombre": "Eje Alimentario – Cambio de Entorno", "origen": "Alimentos + Economía + Administración",
     "acciones": ["Normativa: prohibición bebidas azucaradas en escuelas y espacios públicos", "Sello Comida Mexiquense Saludable", "Apoyos condicionados: transferencias con canasta sana"],
     "meta": "-40% consumo azúcar añadido"},
    {"numero": 4, "nombre": "Eje Tecnológico – Acceso Universal", "origen": "Informática + Gestión + Geografía",
     "acciones": ["Plataforma Edomex Diabetes Conecta — SMS, app ligera, sin internet", "Un solo expediente: SEDESA + ISSEMYM + DIF", "Detección móvil en colonias alejadas"],
     "meta": "Cobertura 95% de pacientes registrados"},
    {"numero": 5, "nombre": "Eje Económico – Protección y Viabilidad", "origen": "Economía + Finanzas + Políticas",
     "acciones": ["Gratuidad total: medicamentos, tiras, consultas, estudios", "Apoyo mensual $1,000 para personas en pobreza extrema", "Presupuesto etiquetado: 15% salud → retorno 5:1"],
     "meta": "Eliminar gasto catastrófico en 100% de familias"},
    {"numero": 6, "nombre": "Eje Urbano – Ciudad Saludable", "origen": "Ingeniería + Geografía + Administración",
     "acciones": ["Regulación: parques, banquetas, alumbrado en nuevos fraccionamientos", "Recuperación de espacios para actividad física", "Seguridad en espacios públicos"],
     "meta": "+25% de espacios activos en zonas de riesgo"},
]

PERFILES_SNII = [
    {"titulo": "Investigador/a en Educación Intercultural y Salud", "area": "Educación / Humanidades", "nivel": "SNII I – II", "funcion": "Lidera ejes 1 y 2; vincula CECyTEM con comunidades"},
    {"titulo": "Investigador/a en Tecnología de Alimentos y Nutrición", "area": "Biotecnología / Ingeniería", "nivel": "SNII I – II", "funcion": "Eje 3; genera comida sana, aceptada y económica"},
    {"titulo": "Investigador/a en Economía de la Salud y Políticas Públicas", "area": "Ciencias Económico-Administrativas", "nivel": "SNII II – III", "funcion": "Eje 5; garantiza financiabilidad, ahorro y sostenibilidad"},
    {"titulo": "Investigador/a en Tecnologías de la Información y Sistemas de Salud", "area": "Ingeniería / Computación", "nivel": "SNII I – II", "funcion": "Eje 4; construye la plataforma y conecta instituciones"},
    {"titulo": "Investigador/a en Geografía de la Salud y Planeación Territorial", "area": "Ciencias Sociales / Ingeniería", "nivel": "SNII II", "funcion": "Ejes 1 y 6; define dónde intervenir, diseño de ciudad saludable"},
]

PROYECTO = {
    "slug": "edomex-diabetes",
    "nombre": "EDOMEX DIABETES: SISTEMA INTEGRAL DE PREVENCIÓN Y CONTROL 2026–2032",
    "objetivo": "Reducir prevalencia en 20%, mejorar control glucémico en 40%, reducir mortalidad en 25%",
    "enfoque": "Atacar causas, no solo efectos — reordenamiento sistémico con fronesis equilibrada",
    "analogia": {
        "titulo": "La diabetes es como una ciudad mal construida",
        "elementos": [
            {"parte": "Cimientos", "representa": "Economía y cultura"},
            {"parte": "Calles", "representa": "Alimentación y educación"},
            {"parte": "Servicios", "representa": "Salud y apoyos"},
        ],
        "principio": "Solución = Reordenamiento sistémico, proporcional, accesible, culturalmente adecuado, económicamente viable",
    },
    "metas_globales": {"prevalencia": "-20%", "control_glucemico": "+40%", "mortalidad": "-25%"},
    "indicadores": {
        "pacientes_totales": 1900000,
        "sin_diagnosticar": 8.2,
        "control_adecuado": 31,
        "costo_anual_mdp": 9200,
        "gasto_familiar_anual": "18,000–25,000 MXN",
    },
}

FUENTES = [
    {"nombre": "SEDESA", "tipo": "gubernamental", "nivel_confiabilidad": 98},
    {"nombre": "INEGI", "tipo": "gubernamental", "nivel_confiabilidad": 97},
    {"nombre": "CONACYT / SECIHTI", "tipo": "gubernamental", "nivel_confiabilidad": 95},
    {"nombre": "SNI", "tipo": "academica", "nivel_confiabilidad": 96},
    {"nombre": "CECyTEM", "tipo": "academica", "nivel_confiabilidad": 94},
    {"nombre": "OMS/OPS", "tipo": "internacional", "nivel_confiabilidad": 95},
]

SABERES = [
    {"titulo": "Medicina tradicional mazahua para control glucémico", "comunidad": "mazahua",
     "descripcion": "Uso de plantas medicinales y prácticas comunitarias de alimentación",
     "aplicacion_salud": "Complemento a tratamiento alópata con mayor apego comunitario", "fuente": "Trabajo de campo CECyTEM"},
    {"titulo": "Conocimiento otomí sobre alimentación tradicional", "comunidad": "otomi",
     "descripcion": "Dieta basada en maíz, frijol y quelites con bajo índice glucémico",
     "aplicacion_salud": "Recuperación de patrones alimentarios saludables", "fuente": "Comunidades San Felipe del Progreso"},
    {"titulo": "Prácticas comunitarias de actividad física", "comunidad": "mazahua",
     "descripcion": "Danza y trabajo comunitario como ejercicio integrado",
     "aplicacion_salud": "Reducción de sedentarismo con enfoque cultural", "fuente": "Antropología aplicada"},
]

LECCIONES = [
    {"titulo": "Modelo por etapas ISSEMYM", "sector": "salud", "institucion": "ISSEMYM",
     "descripcion": "Atención escalonada según gravedad del paciente", "impacto_medido": "-28% hospitalizaciones", "anio": 2024},
    {"titulo": "Agentes multiplicadores CECyTEM", "sector": "educacion", "institucion": "CECyTEM",
     "descripcion": "Estudiantes como promotores de salud en comunidades", "impacto_medido": "78% mejora de conocimientos", "anio": 2025},
    {"titulo": "Transferencias condicionadas DIF", "sector": "desarrollo", "institucion": "DIF",
     "descripcion": "Apoyos alimentarios vinculados a canasta saludable", "impacto_medido": "Reducción 15% gasto catastrófico", "anio": 2024},
]

INDICADORES = [
    {"sector": "salud", "nombre": "Prevalencia de diabetes", "valor_actual": 15.6, "meta": 12.5, "unidad": "%", "tendencia": "descendente"},
    {"sector": "salud", "nombre": "Control glucémico adecuado", "valor_actual": 31, "meta": 43, "unidad": "%", "tendencia": "ascendente"},
    {"sector": "salud", "nombre": "Mortalidad por diabetes", "valor_actual": 104, "meta": 78, "unidad": "por 100 mil", "tendencia": "descendente"},
    {"sector": "educacion", "nombre": "Familias con cambio de hábitos", "valor_actual": 35, "meta": 70, "unidad": "%", "tendencia": "ascendente"},
    {"sector": "desarrollo", "nombre": "Familias sin gasto catastrófico", "valor_actual": 58, "meta": 100, "unidad": "%", "tendencia": "ascendente"},
    {"sector": "urbano", "nombre": "Espacios activos en zonas de riesgo", "valor_actual": 42, "meta": 67, "unidad": "%", "tendencia": "ascendente"},
]

INICIATIVA_LEY = {
    "titulo": "Iniciativa de Ley de Obligatoriedad del Dictamen MITA",
    "descripcion": "Reforma para hacer obligatorio el Dictamen de Validación MITA en toda iniciativa pública del Estado de México.",
    "articulos": [
        "Art. 1: Toda iniciativa pública requiere Dictamen de Validación MITA",
        "Art. 2: Plazo máximo de emisión: 30 días hábiles",
        "Art. 3: Trazabilidad y auditoría obligatoria",
        "Art. 4: Integración intercultural y transdisciplinaria obligatoria",
    ],
}

MUNICIPIOS_EDOMEX = [
    'Ecatepec', 'Nezahualcóyotl', 'Toluca', 'Naucalpan', 'Tlalnepantla',
    'Chimalhuacán', 'Ixtapaluca', 'Cuautitlán Izcalli', 'Tultitlán', 'Chalco',
    'Valle de Chalco', 'Metepec', 'Lerma', 'Texcoco', 'Atizapán de Zaragoza',
    'Coacalco', 'Tecámac', 'Zumpango', 'Atlacomulco', 'El Oro',
]

PUNTOS_ATENCION_EDOMEX = [
    # Salud: ver core/centros_salud_edomex.py — catálogo ISSEM/SEDESA (cargado aparte en seed)
    # Educación — escuelas
    {"slug": "sec-neza-1", "nombre": "Secundaria Técnica No. 45 Nezahualcóyotl", "eje": "educacion", "tipo": "Secundaria",
     "municipio": "Nezahualcóyotl", "lat": 19.4100, "lng": -99.0200, "direccion": "Calle 5 de Mayo, Nezahualcóyotl",
     "telefono": "55-5794-1100", "horario": "Matutino 7:00–14:00", "descripcion": "SEIEM — atención a problemáticas escolares."},
    {"slug": "cecyctem-ecatepec", "nombre": "CECyTEM Plantel Ecatepec", "eje": "educacion", "tipo": "Bachillerato técnico",
     "municipio": "Ecatepec", "lat": 19.5900, "lng": -99.0400, "direccion": "Av. Central s/n, Ecatepec",
     "telefono": "55-5779-8800", "horario": "L–V 7:00–15:00", "descripcion": "Educación media superior y becas."},
    {"slug": "prim-chalco", "nombre": "Escuela Primaria Benito Juárez", "eje": "educacion", "tipo": "Primaria",
     "municipio": "Chalco", "lat": 19.2650, "lng": -98.8950, "direccion": "Calle Hidalgo 50, Chalco",
     "telefono": "55-5971-3300", "horario": "Matutino", "descripcion": "Infraestructura y acceso escolar."},
    {"slug": "prep-toluca", "nombre": "Preparatoria Oficial Toluca", "eje": "educacion", "tipo": "Preparatoria",
     "municipio": "Toluca", "lat": 19.2850, "lng": -99.6500, "direccion": "Av. Juárez Poniente 300, Toluca",
     "telefono": "722-215-4400", "horario": "Matutino y vespertino", "descripcion": "SEIEM — becas y calidad docente."},
    # Empleo — módulos y ferias
    {"slug": "mod-trabajo-toluca", "nombre": "Módulo de Empleo Toluca", "eje": "empleo", "tipo": "Módulo del trabajador",
     "municipio": "Toluca", "lat": 19.2870, "lng": -99.6530, "direccion": "Av. Independencia 1000, Toluca",
     "telefono": "722-215-9000", "horario": "L–V 9:00–17:00", "descripcion": "Secretaría del Trabajo — bolsa de empleo estatal."},
    {"slug": "feria-ecatepec", "nombre": "Feria de Empleo Ecatepec", "eje": "empleo", "tipo": "Feria de empleo",
     "municipio": "Ecatepec", "lat": 19.6050, "lng": -99.0550, "direccion": "Centro Cívico Ecatepec",
     "telefono": "55-5777-9100", "horario": "Mensual — consultar fechas", "descripcion": "Vinculación con empresas del Corredor Oriente."},
    {"slug": "stps-neza", "nombre": "Delegación STPS Nezahualcóyotl", "eje": "empleo", "tipo": "Oficina STPS",
     "municipio": "Nezahualcóyotl", "lat": 19.3950, "lng": -99.0100, "direccion": "Av. Moctezuma 200, Nezahualcóyotl",
     "telefono": "55-5793-7700", "horario": "L–V 9:00–16:00", "descripcion": "Capacitación y derechos laborales."},
    {"slug": "cecyctem-empleo", "nombre": "CECyTEM — Vinculación Laboral", "eje": "empleo", "tipo": "Centro de capacitación",
     "municipio": "Metepec", "lat": 19.2517, "lng": -99.6044, "direccion": "Av. Estado de México 100, Metepec",
     "telefono": "722-271-5500", "horario": "L–V 8:00–16:00", "descripcion": "Capacitación técnica e inserción laboral."},
    # Seguridad
    {"slug": "c5-edomex", "nombre": "C5 Edomex — Centro de Comando", "eje": "seguridad", "tipo": "Emergencias 911",
     "municipio": "Toluca", "lat": 19.2800, "lng": -99.6600, "direccion": "Toluca, Estado de México",
     "telefono": "911", "horario": "24 horas", "descripcion": "Emergencias y patrullaje coordinado."},
    {"slug": "fiscalia-ecatepec", "nombre": "Fiscalía Regional Ecatepec", "eje": "seguridad", "tipo": "Ministerio Público",
     "municipio": "Ecatepec", "lat": 19.5980, "lng": -99.0480, "direccion": "Av. Insurgentes, Ecatepec",
     "telefono": "55-5777-6000", "horario": "L–V 9:00–18:00", "descripcion": "Denuncias y carpetas de investigación."},
    {"slug": "cmd-metepec", "nombre": "Comandancia Metepec", "eje": "seguridad", "tipo": "Policía estatal",
     "municipio": "Metepec", "lat": 19.2530, "lng": -99.6020, "direccion": "Av. Tecnológico, Metepec",
     "telefono": "722-271-0800", "horario": "24 horas", "descripcion": "Patrullaje y atención a denuncias."},
    # Economía
    {"slug": "dif-toluca", "nombre": "DIF Estado de México — Toluca", "eje": "economia", "tipo": "Apoyos sociales",
     "municipio": "Toluca", "lat": 19.2830, "lng": -99.6580, "direccion": "Paseo Tollocan 200, Toluca",
     "telefono": "722-215-3000", "horario": "L–V 9:00–15:00", "descripcion": "Programas sociales y apoyos económicos."},
    {"slug": "finanzas-edomex", "nombre": "Secretaría de Finanzas Edomex", "eje": "economia", "tipo": "Ventanilla fiscal",
     "municipio": "Toluca", "lat": 19.2810, "lng": -99.6570, "direccion": "Ciudad Administrativa, Toluca",
     "telefono": "722-215-2000", "horario": "L–V 9:00–16:00", "descripcion": "Trámites fiscales y programas de apoyo."},
    # Corrupción
    {"slug": "contraloria-edomex", "nombre": "Contraloría del Estado de México", "eje": "corrupcion", "tipo": "Denuncia ciudadana",
     "municipio": "Toluca", "lat": 19.2790, "lng": -99.6590, "direccion": "Ciudad Administrativa, Toluca",
     "telefono": "722-215-7000", "horario": "L–V 9:00–17:00", "descripcion": "Denuncias de actos de corrupción."},
    {"slug": "fgjem-neza", "nombre": "Fiscalía Anticorrupción Nezahualcóyotl", "eje": "corrupcion", "tipo": "Investigación",
     "municipio": "Nezahualcóyotl", "lat": 19.3980, "lng": -99.0120, "direccion": "Av. Chimalhuacán 500, Nezahualcóyotl",
     "telefono": "55-5793-6000", "horario": "L–V 9:00–18:00", "descripcion": "Investigación de hechos de corrupción."},
]
