# Generated by Django 5.2.14 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorImpacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('desarrollo', 'Desarrollo Social'), ('urbano', 'Urbano'), ('economico', 'Económico')], max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('valor_actual', models.FloatField()),
                ('meta', models.FloatField()),
                ('unidad', models.CharField(max_length=50)),
                ('tendencia', models.CharField(default='estable', max_length=20)),
            ],
            options={
                'verbose_name': 'Indicador de impacto',
                'verbose_name_plural': 'Indicadores de impacto',
                'ordering': ['sector', 'nombre'],
            },
        ),
    ]
