# Generated by Django 5.2.14 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Capa geográfica',
                'verbose_name_plural': 'Capas geográficas',
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('hotspot', 'Hotspot'), ('media', 'Media'), ('baja', 'Baja')], max_length=20)),
                ('corredor', models.CharField(choices=[('oriente', 'Corredor Oriente'), ('conurbada', 'Zona Conurbada'), ('indigena', 'Región Indígena'), ('poniente', 'Norte y Poniente')], max_length=20)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('prevalencia', models.FloatField()),
                ('mortalidad', models.FloatField()),
                ('pobreza', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Zona geográfica',
                'verbose_name_plural': 'Zonas geográficas',
                'ordering': ['-prevalencia'],
            },
        ),
    ]
