# Generated by Django 5.2.14 on 2026-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoespacial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoAtencionEdomex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('eje', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('empleo', 'Empleo'), ('seguridad', 'Seguridad'), ('economia', 'Economía'), ('corrupcion', 'Corrupción')], max_length=20)),
                ('tipo', models.CharField(max_length=80)),
                ('municipio', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('horario', models.CharField(blank=True, max_length=120)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Punto de atención Edomex',
                'verbose_name_plural': 'Puntos de atención Edomex',
                'ordering': ['eje', 'municipio', 'nombre'],
            },
        ),
    ]
