# Generated by Django 5.1.5 on 2026-05-28 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoespacial', '0002_puntoatencionedomex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntoatencionedomex',
            name='eje',
            field=models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('empleo', 'Empleo'), ('seguridad', 'Seguridad'), ('economia', 'Economía'), ('corrupcion', 'Corrupción'), ('agua', 'Agua')], max_length=20),
        ),
    ]
