# Generated by Django 5.2.14 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaberTradicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('comunidad', models.CharField(choices=[('mazahua', 'Mazahua'), ('otomi', 'Otomí'), ('nahuatl', 'Náhuatl'), ('mixteco', 'Mixteco'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('aplicacion_salud', models.TextField()),
                ('validado', models.BooleanField(default=True)),
                ('fuente', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Saber tradicional',
                'verbose_name_plural': 'Saberes tradicionales',
                'ordering': ['comunidad', 'titulo'],
            },
        ),
    ]
