# Generated by Django 5.2.14 on 2026-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IniciativaLegislativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('articulos', models.JSONField(default=list)),
                ('estado', models.CharField(default='propuesta', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Iniciativa legislativa',
                'verbose_name_plural': 'Iniciativas legislativas',
            },
        ),
    ]
