# Generated by Django 5.2.14 on 2026-05-25 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CruceInterdisciplinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplinas_texto', models.JSONField(default=list)),
                ('concepto', models.CharField(max_length=200)),
                ('resultado', models.TextField()),
            ],
            options={
                'verbose_name': 'Cruce interdisciplinario',
                'verbose_name_plural': 'Cruces interdisciplinarios',
            },
        ),
        migrations.CreateModel(
            name='EjeMITA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5)),
                ('descripcion', models.TextField()),
                ('proposito', models.TextField()),
                ('fuentes', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Eje MITA',
                'verbose_name_plural': 'Ejes MITA',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PasoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.PositiveSmallIntegerField(unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Paso del proceso',
                'verbose_name_plural': 'Pasos del proceso',
                'ordering': ['paso'],
            },
        ),
        migrations.CreateModel(
            name='PropuestaEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('solicitante', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_analisis', 'En análisis'), ('dictaminado', 'Dictaminado'), ('seguimiento', 'En seguimiento')], default='borrador', max_length=20)),
                ('criterios', models.JSONField(default=dict)),
                ('puntuacion_total', models.FloatField(blank=True, null=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Propuesta de evaluación',
                'verbose_name_plural': 'Propuestas de evaluación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Dictamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=50, unique=True)),
                ('resultado', models.CharField(max_length=30)),
                ('puntuacion', models.FloatField()),
                ('nivel_fronesis', models.BooleanField(default=False)),
                ('evaluacion_completa', models.JSONField(default=dict)),
                ('pdf_archivo', models.FileField(blank=True, upload_to='dictamenes/')),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('propuesta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dictamen', to='mita_engine.propuestaevaluacion')),
            ],
            options={
                'verbose_name': 'Dictamen MITA',
                'verbose_name_plural': 'Dictámenes MITA',
                'ordering': ['-emitido_en'],
            },
        ),
    ]
