# Generated by Django 5.2.14 on 2026-05-25 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mita_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField(blank=True)),
                ('solicitante', models.CharField(blank=True, max_length=200)),
                ('dependencia', models.CharField(blank=True, max_length=200)),
                ('paso_actual', models.PositiveSmallIntegerField(default=1)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('en_proceso', 'En proceso'), ('pendiente_revision', 'Pendiente de revisión'), ('dictaminado', 'Dictaminado'), ('en_seguimiento', 'En seguimiento'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='borrador', max_length=25)),
                ('plazo_limite', models.DateTimeField(blank=True, null=True)),
                ('disciplinas_ids', models.JSONField(blank=True, default=list)),
                ('evaluacion', models.JSONField(blank=True, null=True)),
                ('artefactos', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL)),
                ('propuesta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expediente', to='mita_engine.propuestaevaluacion')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente MITA',
                'verbose_name_plural': 'Expedientes MITA',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='OpcionSolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('puntuacion', models.FloatField(default=0)),
                ('fundamento', models.TextField(blank=True)),
                ('seleccionada', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='mita_engine.expediente')),
            ],
            options={
                'verbose_name': 'Opción de solución',
                'verbose_name_plural': 'Opciones de solución',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='TareaExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('completar_paso', 'Completar paso'), ('revisar', 'Revisar'), ('firmar', 'Firmar dictamen'), ('seguimiento', 'Seguimiento')], default='completar_paso', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('rol_requerido', models.CharField(blank=True, max_length=20)),
                ('completada', models.BooleanField(default=False)),
                ('prioridad', models.PositiveSmallIntegerField(default=5)),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('completada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_mita', to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='mita_engine.expediente')),
            ],
            options={
                'verbose_name': 'Tarea de expediente',
                'verbose_name_plural': 'Tareas de expediente',
                'ordering': ['-prioridad', 'vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='TransicionExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paso_anterior', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('paso_nuevo', models.PositiveSmallIntegerField()),
                ('estado_anterior', models.CharField(blank=True, max_length=25)),
                ('estado_nuevo', models.CharField(max_length=25)),
                ('accion', models.CharField(max_length=50)),
                ('comentario', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transiciones', to='mita_engine.expediente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transición de expediente',
                'verbose_name_plural': 'Transiciones de expediente',
                'ordering': ['creado_en'],
            },
        ),
    ]
